const projects = [
  {
    id: 'menu-project',
    link: '',
    title: 'Menu',
    image: '',
    description: 'Restaurant website',
  },
  {
    id: 'emerald',
    link: 'emerald',
    title: 'Emerald',
    classname: 'dark-text',
    image: '',
    description: 'Sample website for a design agency',
  },
  {
    id: 'finance-village',
    link: 'finance-village',
    title: 'Finance Village',
    image: '',
    description: 'Kenyan financial market information hub.',
  },
  {
    id: 'zenith',
    link: 'zenith',
    title: 'Zenith',
    image: '',
    description: 'Sample portfolio site for tech company',
  },
  {
    id: 'mini-wiki',
    link: 'mini-wiki',
    title: 'Mini Wiki',
    description: 'Small website mirroring Wikipedia',
  },
  {
    id: 'acalc',
    link: 'acalc',
    title: 'ACalc',
    image: '',
    description: 'Small Material Design Calculator',
  },
  {
    id: 'foodhut',
    link: 'foodhut',
    title: 'Food Hut',
    image: '',
    description: 'Simple Food website displaying restaurants and their menus',
  },
  {
    id: 'moviereel',
    link: 'moviereel',
    title: 'MovieReel',
    image: '',
    description: 'Movie app that keeps you updated on the latest movies',
  },
  {
    id: 'treasuregram',
    link: 'treasuregram',
    title: 'TreasureGram',
    image: '',
    description: 'Tresure Photo gallery to store all your precious treasures.',
  },
  {
    id: 'pomodoroclock',
    link: 'pomodoroclock',
    title: 'Pomodoro Clock',
    image: '',
    description: 'Tiny Pomodoro clock',
  },
  {
    id: 'quotemachine',
    link: 'quotemachine',
    title: 'Quote Machine',
    image: '',
    description: 'Small app that generates random quotes',
  },
  {
    id: 'jscalculator',
    link: 'jscalculator',
    title: 'Calculator',
    image: '',
    description: 'Yes, a very simplistic calculator',
  },
  {
    id: 'markdownjournal',
    link: 'markdownjournal',
    title: 'Markdown Journal',
    image: '',
    description: 'Markdown Editor',
  },
  {
    id: 'devconference',
    link: 'devcon',
    title: 'DevConference',
    image: '',
    description: 'Minimalistic Conference site',
  },
  {
    id: 'hadithi',
    link: 'hadithi',
    title: 'Hadithi',
    image: '',
    description: 'Blog for African Stories',
  },
  {
    id: 'tictactoe',
    link: 'tictactoe',
    title: 'TicTacToe',
    image: '',
    description: 'Retro tic tac toe',
  },
  {
    id: 'simongame',
    link: 'simongame',
    title: 'Simon Says',
    image: '',
    description: 'Remember the simon game?',
  },
  {
    id: 'camperleaderboard',
    link: 'camperleaderboard',
    title: 'Leaderboard',
    image: '',
    description: 'FCC Camper Leaderboard',
  },
];

export default projects;
