name: Danger CI

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  test:
    name: Danger CI

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      id: bun-setup
      with:
        bun-version: latest

    - name: Install dependencies
      if: steps.bun-setup.cache-hit != 'true'
      run: bun install
    
    - name: Danger CI Check
      uses: danger/danger-js@9.1.8
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
