name: Deploy

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  deploy:
    name: Deploy

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      id: bun-setup
      with:
        bun-version: latest

    - name: Install dependencies
      if: steps.bun-setup.cache-hit != 'true'
      run: bun install

    - name: Build Staging
      if: github.ref == 'refs/heads/develop'
      run: bun run build
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ENV: staging
        SENTRY_TRACES_SAMPLE_RATE: 1.0
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

    - name: Deploy Staging
      if: github.ref == 'refs/heads/develop'
      run: bun run deploy:staging -- --token ${{ secrets.SURGE_TOKEN }}

    - name: Build Production
      if: github.ref == 'refs/heads/main'
      run: |
        bun run build
        mv build docs
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ENV: production
        SENTRY_TRACES_SAMPLE_RATE: 0.5
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

    # - name: Push Production
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     git config --global user.name github-actions
    #     git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'      
    #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    #     git add docs
    #     git commit -am "updating docs" ||  true
    #     git push --force origin HEAD:$GITHUB_REF || true
