# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
name: Docker Build

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed
    branches:
      - "main"
      - "develop"
  push:
    branches: [ main, develop ]

jobs:
  build_application:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Application
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

      - name: Upload build artifact
        continue-on-error: false
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/

  push_to_registries:
    name: Pushes Docker image to Dockerhub and Github Registry
    needs: build_application
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Set Up Qemu
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
