name: Lint

on: [push]

jobs:
  lint:
    name: Lint
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

      # Ref: https://github.com/hadolint/hadolint-action
    - uses: hadolint/hadolint-action@v3.1.0
      id: hadolint
      with:
        dockerfile: Dockerfile
        config: '.hadolint.yaml'

    # Ref: https://github.com/actions/github-script
    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const output = `
          #### Hadolint: \`${{ steps.hadolint.outcome }}\`
          \`\`\`
          ${process.env.HADOLINT_RESULTS}
          \`\`\`
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - uses: oven-sh/setup-bun@v2
      id: bun-setup
      with:
        bun-version: latest

    - name: Install dependencies
      if: steps.bun-setup.cache-hit != 'true'
      run: bun install

    - name: Lint Code
      run: bun run lint

    - name: Lint Styles
      run: bun run lint:styles
