name: Sentry Release

on: 
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  release:
    name: Sentry Release

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      id: bun-setup
      with:
        bun-version: latest

    - name: Run Staging Build
      if: github.ref_name == 'develop'
      run: bun run build
      env:
        VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        VITE_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        VITE_ENV: staging
        VITE_NODE_ENV: staging
        VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        VITE_BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

    # Ref: https://github.com/getsentry/action-release
    - name: Create Sentry Staging release
      if: github.ref_name == 'develop'
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: staging
        sourcemaps: ./dist/static/js

    - name: Run Production Build
      if: github.ref_name == 'main'
      run: bun run build
      env:
        VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        VITE_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        VITE_ENV: production
        VITE_NODE_ENV: production
        VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        VITE_BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

    - name: Create Sentry Production release
      if: github.ref_name == 'main'
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: ./dist/static/js
