name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint & Test
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
    
    - name: Unit Tests
      run: yarn test
      env:
        CI: true

    - name: Build
      run: yarn build --if-present