name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Unit Tests

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      id: bun-setup
      with:
        bun-version: latest

    - name: Install dependencies
      if: steps.bun-setup.cache-hit != 'true'
      run: bun install

    - name: Unit Tests
      run: bun run test:coverage
      continue-on-error: true
      env:
        CI: true
    
    - name: Test Reporters
      run: bun run test:reporters
      continue-on-error: true
      env:
        CI: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # Ref: https://github.com/codecov/codecov-action
    - name: Upload Test Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: false
        verbose: true
